services:
  web:
    container_name: app_web
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
      - ../.venv/:/app/.venv:rw
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: app_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
